<?php

class CategoriesTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('categories')->delete();
        
		\DB::table('categories')->insert(array (
			0 => 
			array (
				'id' => 1,
				'name' => 'Indoor Signage',
				'short_name' => 'indoor-signage',
				'meta_title' => '',
				'meta_description' => '',
			'description' => '<span style="color: rgb(63, 63, 63); font-family: \'Open Sans\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: normal;">We can also reverse print our graphics onto the acrylic to avoid wear and tear on the graphic</span>',
				'home_description' => '',
				'color' => '#0b6635',
				'order_no' => 1,
				'parent_id' => 0,
				'menu_id' => 80,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-07-11 08:28:07',
			),
			1 => 
			array (
				'id' => 2,
				'name' => 'Event Signage',
				'short_name' => 'event-signage',
				'meta_title' => '',
				'meta_description' => '',
			'description' => '<p><span style="color: rgb(63, 63, 63); font-family: \'Open Sans\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: normal;">Easy to assemble and take-down, these magnet-mounted panels are built for durability, flexibility and longevity.</span></p>
',
				'home_description' => '',
				'color' => '#257bab',
				'order_no' => 2,
				'parent_id' => 0,
				'menu_id' => 81,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-07-11 08:47:52',
			),
			2 => 
			array (
				'id' => 3,
				'name' => 'Outdoor Signage',
				'short_name' => 'outdoor-signage',
				'meta_title' => '',
				'meta_description' => '',
				'description' => 'Use outdoor signs to inform the passer-bys about &nbsp;your company.',
				'home_description' => '',
				'color' => '#b3573a',
				'order_no' => 3,
				'parent_id' => 0,
				'menu_id' => 82,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-07-11 08:49:17',
			),
			3 => 
			array (
				'id' => 5,
				'name' => 'Tacky Products',
				'short_name' => 'tacky-products',
				'meta_title' => '',
				'meta_description' => '',
				'description' => 'Take any high resolution, digital image and put it on your wall as a custom cut-out.',
				'home_description' => '',
				'color' => '#1c8e9e',
				'order_no' => 4,
				'parent_id' => 0,
				'menu_id' => 79,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-07-11 08:50:43',
			),
			4 => 
			array (
				'id' => 6,
				'name' => 'Canvas',
				'short_name' => 'canvas',
				'meta_title' => '',
				'meta_description' => '',
				'description' => 'test',
			'home_description' => '&lt;span style=&quot;color: rgb(63, 63, 63); font-family: &#039;Open Sans&#039;, Arial, Helvetica, sans-serif; font-size: 14px; line-height: normal;&quot;&gt;The Imagestylor Canvas is the latest and most innovative product in our wall art decor line&lt;/span&gt;',
				'color' => '#ffffff',
				'order_no' => 1,
				'parent_id' => 1,
				'menu_id' => 119,
				'on_home' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-07-24 12:04:47',
			),
			5 => 
			array (
				'id' => 7,
				'name' => 'Decal & Murals',
				'short_name' => 'decal-murals',
				'meta_title' => '',
				'meta_description' => '',
				'description' => '',
				'home_description' => '',
				'color' => '#ffffff',
				'order_no' => 2,
				'parent_id' => 1,
				'menu_id' => 84,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-07-10 12:00:39',
			),
			6 => 
			array (
				'id' => 8,
				'name' => 'Banner',
				'short_name' => 'banner',
				'meta_title' => '',
				'meta_description' => '',
				'description' => '',
				'home_description' => '',
				'color' => '#ffffff',
				'order_no' => 3,
				'parent_id' => 1,
				'menu_id' => 120,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-07-24 05:05:56',
			),
			7 => 
			array (
				'id' => 9,
				'name' => 'Image Box',
				'short_name' => 'image-box',
				'meta_title' => '',
				'meta_description' => '',
				'description' => '',
				'home_description' => '',
				'color' => '#ffffff',
				'order_no' => 4,
				'parent_id' => 1,
				'menu_id' => 86,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-07-10 12:00:45',
			),
			8 => 
			array (
				'id' => 10,
				'name' => 'Banner Stand',
				'short_name' => 'banner-stand',
				'meta_title' => '',
				'meta_description' => '',
				'description' => '',
				'home_description' => '',
				'color' => '#ffffff',
				'order_no' => 1,
				'parent_id' => 2,
				'menu_id' => 87,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-07-10 12:00:49',
			),
			9 => 
			array (
				'id' => 11,
				'name' => 'Event Signage other',
				'short_name' => 'event-signage-other',
				'meta_title' => '',
				'meta_description' => '',
				'description' => '',
				'home_description' => '',
				'color' => '#ffffff',
				'order_no' => 2,
				'parent_id' => 2,
				'menu_id' => 88,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-07-10 12:00:51',
			),
			10 => 
			array (
				'id' => 12,
				'name' => 'Outdoor',
				'short_name' => 'outdoor',
				'meta_title' => '',
				'meta_description' => '',
				'description' => '',
				'home_description' => '',
				'color' => '#b31717',
				'order_no' => 1,
				'parent_id' => 3,
				'menu_id' => 89,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-07-23 22:25:08',
			),
			11 => 
			array (
				'id' => 13,
				'name' => 'Decals',
				'short_name' => 'decals',
				'meta_title' => '',
				'meta_description' => '',
				'description' => '',
				'home_description' => 'Image-Tex&trade; comes in several different sizes, and can be cut to suit your needs',
				'color' => '#ffffff',
				'order_no' => 1,
				'parent_id' => 5,
				'menu_id' => 90,
				'on_home' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '0000-00-00 00:00:00',
				'updated_at' => '2015-07-24 12:04:47',
			),
			12 => 
			array (
				'id' => 14,
				'name' => 'Murals',
				'short_name' => 'murals',
				'meta_title' => '',
				'meta_description' => '',
				'description' => '',
				'home_description' => '',
				'color' => '#ffffff',
				'order_no' => 2,
				'parent_id' => 5,
				'menu_id' => 91,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 11:59:33',
				'updated_at' => '2015-07-10 12:01:01',
			),
			13 => 
			array (
				'id' => 15,
				'name' => 'Specialty',
				'short_name' => 'specialty',
				'meta_title' => '',
				'meta_description' => '',
				'description' => 'A test',
				'home_description' => '',
				'color' => '#ffffff',
				'order_no' => 1,
				'parent_id' => 0,
				'menu_id' => 116,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-23 22:15:13',
				'updated_at' => '2015-07-23 22:18:44',
			),
			14 => 
			array (
				'id' => 16,
				'name' => 'Wall Art',
				'short_name' => 'wall-art',
				'meta_title' => '',
				'meta_description' => '',
				'description' => '',
				'home_description' => '',
				'color' => '#ffffff',
				'order_no' => 1,
				'parent_id' => 15,
				'menu_id' => 121,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-23 22:41:39',
				'updated_at' => '2015-07-24 09:27:13',
			),
			15 => 
			array (
				'id' => 17,
				'name' => 'Industry Signage',
				'short_name' => 'industry-signage',
				'meta_title' => '',
				'meta_description' => '',
				'description' => '',
				'home_description' => '',
				'color' => '#ffffff',
				'order_no' => 1,
				'parent_id' => 0,
				'menu_id' => 123,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-24 11:26:52',
				'updated_at' => '2015-07-24 11:31:17',
			),
			16 => 
			array (
				'id' => 18,
				'name' => 'Home Builder',
				'short_name' => 'home-builder',
				'meta_title' => '',
				'meta_description' => '',
				'description' => '',
				'home_description' => '',
				'color' => '#ffffff',
				'order_no' => 1,
				'parent_id' => 17,
				'menu_id' => 0,
				'on_home' => 0,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-24 11:30:16',
				'updated_at' => '2015-07-24 11:30:16',
			),
		));
	}

}
