<?php

class MenusTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('menus')->delete();
        
		\DB::table('menus')->insert(array (
			0 => 
			array (
				'id' => 1,
				'name' => 'Dashboard',
				'icon_class' => 'icon-home',
				'link' => 'admin',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 10:27:01',
				'updated_at' => '2015-07-24 02:11:40',
			),
			1 => 
			array (
				'id' => 2,
				'name' => 'Configure',
				'icon_class' => 'fa fa-cogs',
				'link' => 'admin/configures',
				'parent_id' => 55,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 4,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 10:27:02',
				'updated_at' => '2015-07-24 02:12:06',
			),
			2 => 
			array (
				'id' => 3,
				'name' => 'Banner',
				'icon_class' => 'icon-credit-card',
				'link' => 'admin/banners',
				'parent_id' => 52,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 10:27:02',
				'updated_at' => '2015-07-24 02:12:24',
			),
			3 => 
			array (
				'id' => 4,
				'name' => 'Menu',
				'icon_class' => 'icon-list',
				'link' => 'admin/menus',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => NULL,
				'column_no' => 1,
				'order_no' => 3,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 10:27:02',
				'updated_at' => '2015-07-24 11:46:04',
			),
			4 => 
			array (
				'id' => 5,
				'name' => 'User',
				'icon_class' => 'icon-users',
				'link' => 'admin/users',
				'parent_id' => 55,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 10:27:02',
				'updated_at' => '2015-07-24 02:12:06',
			),
			5 => 
			array (
				'id' => 6,
				'name' => 'Admin',
				'icon_class' => 'fa fa-users',
				'link' => 'admin/admins',
				'parent_id' => 55,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 10:27:02',
				'updated_at' => '2015-07-24 02:12:06',
			),
			6 => 
			array (
				'id' => 7,
				'name' => 'Products Group',
				'icon_class' => 'icon-social-dropbox',
				'link' => NULL,
				'parent_id' => 0,
				'type' => 'backend',
				'group' => NULL,
				'column_no' => 1,
				'order_no' => 4,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 10:27:02',
				'updated_at' => '2015-07-24 11:46:04',
			),
			7 => 
			array (
				'id' => 8,
				'name' => 'Product',
				'icon_class' => 'icon-bag',
				'link' => 'admin/products',
				'parent_id' => 7,
				'type' => 'backend',
				'group' => NULL,
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 10:27:02',
				'updated_at' => '2015-07-24 11:46:04',
			),
			8 => 
			array (
				'id' => 9,
				'name' => 'Option Group',
				'icon_class' => 'icon-notebook',
				'link' => 'admin/product-option-groups',
				'parent_id' => 7,
				'type' => 'backend',
				'group' => NULL,
				'column_no' => 1,
				'order_no' => 4,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 10:27:02',
				'updated_at' => '2015-07-24 11:46:04',
			),
			9 => 
			array (
				'id' => 10,
				'name' => 'Option',
				'icon_class' => 'icon-layers',
				'link' => 'admin/product-options',
				'parent_id' => 7,
				'type' => 'backend',
				'group' => NULL,
				'column_no' => 1,
				'order_no' => 5,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 10:27:02',
				'updated_at' => '2015-07-24 11:46:04',
			),
			10 => 
			array (
				'id' => 11,
				'name' => 'Category',
				'icon_class' => 'icon-bar-chart',
				'link' => 'admin/product-categories',
				'parent_id' => 7,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 6,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 10:27:02',
				'updated_at' => '2015-07-24 11:46:04',
			),
			11 => 
			array (
				'id' => 12,
				'name' => 'Layout',
				'icon_class' => 'icon-screen-tablet',
				'link' => 'admin/layouts',
				'parent_id' => 7,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 7,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-17 10:27:02',
				'updated_at' => '2015-07-24 11:46:04',
			),
			12 => 
			array (
				'id' => 37,
				'name' => 'User Feedback',
				'icon_class' => 'icon-feed',
				'link' => 'admin/contacts',
				'parent_id' => 52,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 5,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-21 10:06:32',
				'updated_at' => '2015-07-24 02:12:24',
			),
			13 => 
			array (
				'id' => 38,
				'name' => 'Role',
				'icon_class' => 'fa fa-users',
				'link' => 'admin/roles',
				'parent_id' => 55,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-21 10:06:32',
				'updated_at' => '2015-07-24 02:12:06',
			),
			14 => 
			array (
				'id' => 52,
				'name' => 'Other Content',
				'icon_class' => 'icon-folder',
				'link' => '',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 5,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-25 05:03:32',
				'updated_at' => '2015-07-24 02:12:24',
			),
			15 => 
			array (
				'id' => 53,
				'name' => 'Order',
				'icon_class' => 'icon-basket-loaded',
				'link' => 'admin/orders',
				'parent_id' => 52,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 4,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-25 05:04:31',
				'updated_at' => '2015-07-24 02:12:24',
			),
			16 => 
			array (
				'id' => 54,
				'name' => 'Email Template',
				'icon_class' => 'icon-envelope',
				'link' => 'admin/email-templates',
				'parent_id' => 52,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 6,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-25 05:05:11',
				'updated_at' => '2015-07-24 02:12:24',
			),
			17 => 
			array (
				'id' => 55,
				'name' => 'Admin Group',
				'icon_class' => 'icon-shield',
				'link' => '',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 6,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-04-25 05:05:34',
				'updated_at' => '2015-07-24 02:12:06',
			),
			18 => 
			array (
				'id' => 56,
				'name' => 'Image Stock',
				'icon_class' => 'icon-picture',
				'link' => 'admin/images',
				'parent_id' => 52,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-05-28 05:26:52',
				'updated_at' => '2015-07-24 02:12:24',
			),
			19 => 
			array (
				'id' => 57,
				'name' => 'About us',
				'icon_class' => 'icon-settings',
				'link' => 'aboutus',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 4,
				'order_no' => 1,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-02 10:26:06',
				'updated_at' => '2015-07-24 10:50:31',
			),
			20 => 
			array (
				'id' => 58,
				'name' => 'Home Content',
				'icon_class' => 'icon-grid',
				'link' => 'admin/frontend-home',
				'parent_id' => 0,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-07 13:58:44',
				'updated_at' => '2015-07-24 02:11:51',
			),
			21 => 
			array (
				'id' => 59,
				'name' => 'About us',
				'icon_class' => 'icon-settings',
				'link' => 'pages/about-us',
				'parent_id' => 57,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 4,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 09:36:08',
				'updated_at' => '2015-07-24 10:50:31',
			),
			22 => 
			array (
				'id' => 60,
				'name' => 'Product brochure',
				'icon_class' => 'icon-user',
				'link' => 'product-brochure',
				'parent_id' => 57,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 6,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 09:37:28',
				'updated_at' => '2015-07-24 10:50:31',
			),
			23 => 
			array (
				'id' => 61,
				'name' => 'Events',
				'icon_class' => 'icon-user',
				'link' => 'events',
				'parent_id' => 57,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 5,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 09:38:16',
				'updated_at' => '2015-07-24 10:50:31',
			),
			24 => 
			array (
				'id' => 62,
				'name' => 'Special offers',
				'icon_class' => 'icon-user',
				'link' => 'special-offers ',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 3,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 09:39:04',
				'updated_at' => '2015-07-24 10:50:31',
			),
			25 => 
			array (
				'id' => 63,
				'name' => 'Support',
				'icon_class' => 'icon-user',
				'link' => 'software-support',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 4,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 09:39:52',
				'updated_at' => '2015-07-24 10:50:31',
			),
			26 => 
			array (
				'id' => 64,
				'name' => 'Contact us',
				'icon_class' => 'icon-user',
				'link' => 'pages/contact-us',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 5,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 09:40:38',
				'updated_at' => '2015-07-24 10:50:31',
			),
			27 => 
			array (
				'id' => 66,
				'name' => 'Champion Wall Products',
				'icon_class' => 'icon-user',
				'link' => 'champion-wall-products',
				'parent_id' => 62,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 09:42:06',
				'updated_at' => '2015-07-24 10:50:31',
			),
			28 => 
			array (
				'id' => 67,
				'name' => 'Current offers',
				'icon_class' => 'icon-user',
				'link' => 'current-offers',
				'parent_id' => 62,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 09:43:17',
				'updated_at' => '2015-07-24 10:50:31',
			),
			29 => 
			array (
				'id' => 68,
				'name' => 'Sample offers',
				'icon_class' => 'icon-user',
				'link' => 'sample-offers',
				'parent_id' => 62,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 09:43:59',
				'updated_at' => '2015-07-24 10:50:31',
			),
			30 => 
			array (
				'id' => 69,
				'name' => 'Software',
				'icon_class' => 'icon-user',
				'link' => '',
				'parent_id' => 63,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 09:44:40',
				'updated_at' => '2015-07-24 10:50:31',
			),
			31 => 
			array (
				'id' => 70,
				'name' => ' Online ordering',
				'icon_class' => 'icon-user',
				'link' => ' online-ordering',
				'parent_id' => 69,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 3,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 09:45:30',
				'updated_at' => '2015-07-24 10:50:31',
			),
			32 => 
			array (
				'id' => 71,
				'name' => 'Jobtraq CRM',
				'icon_class' => 'icon-user',
				'link' => 'Jobtraq',
				'parent_id' => 69,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 3,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 10:11:16',
				'updated_at' => '2015-07-24 10:50:31',
			),
			33 => 
			array (
				'id' => 72,
				'name' => 'Support',
				'icon_class' => 'icon-user',
				'link' => 'support',
				'parent_id' => 63,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 10:11:45',
				'updated_at' => '2015-07-24 10:50:31',
			),
			34 => 
			array (
				'id' => 73,
				'name' => 'Colour management',
				'icon_class' => 'icon-user',
				'link' => 'clour-management',
				'parent_id' => 72,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 3,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 10:12:39',
				'updated_at' => '2015-07-24 10:50:31',
			),
			35 => 
			array (
				'id' => 74,
				'name' => 'Useful information',
				'icon_class' => 'icon-user',
				'link' => 'useful-information',
				'parent_id' => 72,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 5,
				'level' => 3,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 10:14:13',
				'updated_at' => '2015-07-24 10:50:31',
			),
			36 => 
			array (
				'id' => 75,
				'name' => 'Credit application form',
				'icon_class' => 'icon-user',
				'link' => 'credit-application-form',
				'parent_id' => 72,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 3,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 10:14:29',
				'updated_at' => '2015-07-24 10:50:31',
			),
			37 => 
			array (
				'id' => 76,
				'name' => 'File preparation',
				'icon_class' => 'icon-user',
				'link' => 'file-preparation',
				'parent_id' => 72,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 3,
				'level' => 3,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 10:15:07',
				'updated_at' => '2015-07-24 10:50:31',
			),
			38 => 
			array (
				'id' => 77,
				'name' => 'Shipping information',
				'icon_class' => 'icon-user',
				'link' => 'shipping-information',
				'parent_id' => 72,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 4,
				'level' => 3,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 10:15:11',
				'updated_at' => '2015-07-24 10:50:31',
			),
			39 => 
			array (
				'id' => 79,
				'name' => 'Tacky Products',
				'icon_class' => '',
				'link' => 'tacky-products',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 11:58:36',
				'updated_at' => '2015-07-24 09:43:53',
			),
			40 => 
			array (
				'id' => 80,
				'name' => 'Indoor Signage',
				'icon_class' => '',
				'link' => 'indoor-signage',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 3,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 11:59:56',
				'updated_at' => '2015-07-24 09:43:53',
			),
			41 => 
			array (
				'id' => 81,
				'name' => 'Event Signage',
				'icon_class' => '',
				'link' => 'event-signage',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 4,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 12:00:06',
				'updated_at' => '2015-07-24 09:43:53',
			),
			42 => 
			array (
				'id' => 82,
				'name' => 'Outdoor Signage',
				'icon_class' => '',
				'link' => 'outdoor-signage',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 5,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 12:00:10',
				'updated_at' => '2015-07-24 09:43:53',
			),
			43 => 
			array (
				'id' => 84,
				'name' => 'Decal & Murals',
				'icon_class' => '',
				'link' => 'decal-murals',
				'parent_id' => 80,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 12:00:39',
				'updated_at' => '2015-07-24 09:43:53',
			),
			44 => 
			array (
				'id' => 86,
				'name' => 'Image Box',
				'icon_class' => 'icon-settings',
				'link' => 'image-box',
				'parent_id' => 80,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 2,
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 12:00:45',
				'updated_at' => '2015-07-24 09:43:53',
			),
			45 => 
			array (
				'id' => 87,
				'name' => 'Banner Stand',
				'icon_class' => '',
				'link' => 'banner-stand',
				'parent_id' => 81,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 12:00:48',
				'updated_at' => '2015-07-24 09:43:53',
			),
			46 => 
			array (
				'id' => 88,
				'name' => 'Event Signage other',
				'icon_class' => '',
				'link' => 'event-signage-other',
				'parent_id' => 81,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 12:00:51',
				'updated_at' => '2015-07-24 09:43:53',
			),
			47 => 
			array (
				'id' => 89,
				'name' => 'Outdoor',
				'icon_class' => '',
				'link' => 'outdoor',
				'parent_id' => 82,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 12:00:54',
				'updated_at' => '2015-07-24 09:43:53',
			),
			48 => 
			array (
				'id' => 90,
				'name' => 'Decals',
				'icon_class' => '',
				'link' => 'decals',
				'parent_id' => 79,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 12:00:58',
				'updated_at' => '2015-07-24 09:43:53',
			),
			49 => 
			array (
				'id' => 91,
				'name' => 'Murals',
				'icon_class' => '',
				'link' => 'murals',
				'parent_id' => 79,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 12:01:01',
				'updated_at' => '2015-07-24 09:43:53',
			),
			50 => 
			array (
				'id' => 92,
				'name' => 'Tabs',
				'icon_class' => 'icon-social-tumblr',
				'link' => 'admin/product-tabs',
				'parent_id' => 7,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-10 15:25:59',
				'updated_at' => '2015-07-24 11:46:04',
			),
			51 => 
			array (
				'id' => 93,
				'name' => 'New Products',
				'icon_class' => 'icon-user',
				'link' => '',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'footer',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:03:37',
				'updated_at' => '2015-07-24 10:58:12',
			),
			52 => 
			array (
				'id' => 94,
				'name' => 'Imagestylor Canvas',
				'icon_class' => 'icon-user',
				'link' => 'indoor-signage/imagestylor-canvas',
				'parent_id' => 93,
				'type' => 'frontend',
				'group' => 'footer',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:08:53',
				'updated_at' => '2015-07-24 11:16:05',
			),
			53 => 
			array (
				'id' => 95,
				'name' => 'Useful links',
				'icon_class' => 'icon-user',
				'link' => '',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'footer',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:13:17',
				'updated_at' => '2015-07-15 15:58:34',
			),
			54 => 
			array (
				'id' => 96,
				'name' => 'About us',
				'icon_class' => 'icon-user',
				'link' => 'pages/about-us',
				'parent_id' => 95,
				'type' => 'frontend',
				'group' => 'footer',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:14:21',
				'updated_at' => '2015-07-15 15:58:34',
			),
			55 => 
			array (
				'id' => 97,
				'name' => 'Contact us',
				'icon_class' => 'icon-user',
				'link' => 'pages/contact-us',
				'parent_id' => 95,
				'type' => 'frontend',
				'group' => 'footer',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-15 15:58:34',
			),
			56 => 
			array (
				'id' => 98,
				'name' => 'Services',
				'icon_class' => '',
				'link' => 'pages/services',
				'parent_id' => 95,
				'type' => 'frontend',
				'group' => 'footer',
				'column_no' => 1,
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-15 15:58:34',
			),
			57 => 
			array (
				'id' => 99,
				'name' => 'Business Solutions',
				'icon_class' => '',
				'link' => 'pages/aec-industry',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-24 10:50:31',
			),
			58 => 
			array (
				'id' => 100,
				'name' => 'AEC Industry',
				'icon_class' => '',
				'link' => 'pages/business-solutions/aec-industry',
				'parent_id' => 99,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-24 10:50:31',
			),
			59 => 
			array (
				'id' => 101,
				'name' => 'Art & Photography',
				'icon_class' => '',
				'link' => 'pages/business-solutions/art-photography',
				'parent_id' => 99,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-24 10:50:31',
			),
			60 => 
			array (
				'id' => 102,
				'name' => 'Cultural & Sporting Events',
				'icon_class' => '',
				'link' => 'pages/business-solutions/cultural-sporting-events',
				'parent_id' => 99,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-24 10:50:31',
			),
			61 => 
			array (
				'id' => 103,
				'name' => 'Golf and Tournament Signage',
				'icon_class' => '',
				'link' => 'pages/business-solutions/golf-and-tournament-signage',
				'parent_id' => 99,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 4,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-24 10:50:31',
			),
			62 => 
			array (
				'id' => 104,
				'name' => 'Governments & Non-Profit',
				'icon_class' => '',
				'link' => 'pages/business-solutions/governments-non-profit',
				'parent_id' => 99,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 5,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-24 10:50:31',
			),
			63 => 
			array (
				'id' => 105,
				'name' => 'Graphic Designers',
				'icon_class' => '',
				'link' => 'pages/business-solutions/graphic-designers',
				'parent_id' => 99,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 6,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-24 10:50:31',
			),
			64 => 
			array (
				'id' => 106,
				'name' => 'Manufacturing & Wholesale',
				'icon_class' => '',
				'link' => 'pages/business-solutions/manufacturing-wholesale',
				'parent_id' => 99,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 7,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-24 10:50:31',
			),
			65 => 
			array (
				'id' => 107,
				'name' => 'Marketing Specialists',
				'icon_class' => '',
				'link' => 'pages/business-solutions/marketing-specialists',
				'parent_id' => 99,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 8,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-24 10:50:31',
			),
			66 => 
			array (
				'id' => 108,
				'name' => 'Real Estate Development',
				'icon_class' => '',
				'link' => 'pages/business-solutions/real-estate-development',
				'parent_id' => 99,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 9,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-24 10:50:31',
			),
			67 => 
			array (
				'id' => 109,
				'name' => 'Retail & Hospitality',
				'icon_class' => '',
				'link' => 'pages/business-solutions/retail-hospitality',
				'parent_id' => 99,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 10,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-24 10:50:31',
			),
			68 => 
			array (
				'id' => 110,
				'name' => 'Testimonials',
				'icon_class' => '',
				'link' => 'pages/testimonials',
				'parent_id' => 57,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 4,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-11 10:16:32',
				'updated_at' => '2015-07-24 10:50:31',
			),
			69 => 
			array (
				'id' => 111,
				'name' => 'Services',
				'icon_class' => 'icon-user',
				'link' => 'pages/services',
				'parent_id' => 57,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 3,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-15 11:09:07',
				'updated_at' => '2015-07-24 10:50:31',
			),
			70 => 
			array (
				'id' => 112,
				'name' => 'Blogs',
				'icon_class' => 'icon-user',
				'link' => 'blogs',
				'parent_id' => 57,
				'type' => 'frontend',
				'group' => 'header',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-15 11:10:01',
				'updated_at' => '2015-07-24 10:50:31',
			),
			71 => 
			array (
				'id' => 114,
				'name' => 'Join the Family',
				'icon_class' => 'icon-settings',
				'link' => 'join-the-family',
				'parent_id' => 95,
				'type' => 'frontend',
				'group' => 'footer',
				'column_no' => 1,
				'order_no' => 4,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-15 15:57:35',
				'updated_at' => '2015-07-15 17:16:28',
			),
			72 => 
			array (
				'id' => 115,
				'name' => 'Pages',
				'icon_class' => 'icon-book-open',
				'link' => 'admin/pages',
				'parent_id' => 52,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-17 15:01:29',
				'updated_at' => '2015-07-24 02:12:24',
			),
			73 => 
			array (
				'id' => 116,
				'name' => 'Specialty',
				'icon_class' => '',
				'link' => 'specialty',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-23 22:16:42',
				'updated_at' => '2015-07-24 09:43:53',
			),
			74 => 
			array (
				'id' => 119,
				'name' => 'Canvas',
				'icon_class' => 'icon-settings',
				'link' => 'canvas',
				'parent_id' => 80,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-24 05:03:40',
				'updated_at' => '2015-07-24 09:43:53',
			),
			75 => 
			array (
				'id' => 120,
				'name' => 'Banner',
				'icon_class' => '',
				'link' => 'banner',
				'parent_id' => 82,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-24 05:05:56',
				'updated_at' => '2015-07-24 09:43:53',
			),
			76 => 
			array (
				'id' => 121,
				'name' => 'Wall Art',
				'icon_class' => '',
				'link' => 'wall-art',
				'parent_id' => 116,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-24 09:27:13',
				'updated_at' => '2015-07-24 09:43:53',
			),
			77 => 
			array (
				'id' => 123,
				'name' => 'Home Builders Signage',
				'icon_class' => '',
				'link' => 'industry-signage',
				'parent_id' => 0,
				'type' => 'frontend',
				'group' => 'product',
				'column_no' => 1,
				'order_no' => 1,
				'level' => 1,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-24 11:27:18',
				'updated_at' => '2015-07-24 11:29:40',
			),
			78 => 
			array (
				'id' => 124,
				'name' => 'Product Offers',
				'icon_class' => 'icon-notebook',
				'link' => 'admin/product-offers',
				'parent_id' => 7,
				'type' => 'backend',
				'group' => '',
				'column_no' => 1,
				'order_no' => 2,
				'level' => 2,
				'active' => 1,
				'created_by' => 0,
				'updated_by' => 0,
				'created_at' => '2015-07-24 11:45:53',
				'updated_at' => '2015-07-24 11:50:00',
			),
		));
	}

}
